import { validateXml, XmlValidationResult } from '../xmlValidator';

jest.mock('../../utils/logger', () => ({
  logError: jest.fn(),
  logInfo: jest.fn(),
  logWarning: jest.fn()
}));

const mockOpts = {
  requestId: 'req-123',
  traceId: 'trace-456',
  spanId: 'span-789',
};

describe('validateXml', () => {
  describe('Basic Validation', () => {
    it('should return isValid=true when XML matches template', () => {
      const xml = '<root><name>John</name></root>';
      const template = '<root><name>John</name></root>';

      const result = validateXml(xml, template, mockOpts);

      expect(result.isValid).toBe(true);
      expect(result.differences).toBeUndefined();
    });

    it('should return isValid=false when XML does not match template', () => {
      const xml = '<root><name>John</name></root>';
      const template = '<root><name>Jane</name></root>';

      const result = validateXml(xml, template, mockOpts);

      expect(result.isValid).toBe(false);
      expect(result.differences).toBeDefined();
      expect(result.differences!.length).toBeGreaterThan(0);
    });
  });

  describe('Result Object Fields', () => {
    it('should include expected and actual on failure', () => {
      const xml = '<root><name>John</name><age>25</age></root>';
      const template = '<root><name>Jane</name><age>30</age></root>';

      const result = validateXml(xml, template, mockOpts);

      expect(result).toHaveProperty('isValid', false);
      expect(result).toHaveProperty('expected');
      expect(result).toHaveProperty('actual');
      expect(result).toHaveProperty('differences');
      expect(result).toHaveProperty('method');
    });

    it('should include method field indicating validation approach', () => {
      const xml = '<root><name>John</name></root>';
      const template = '<root><name>Jane</name></root>';

      const result = validateXml(xml, template, mockOpts);

      expect(result.method).toMatch(/^(diff-js-xml|structural)$/);
    });

    it('should not include htmlReport or s3Url (not generated by validateXml)', () => {
      const xml = '<root><name>John</name></root>';
      const template = '<root><name>Jane</name></root>';

      const result = validateXml(xml, template, mockOpts);

      expect(result.htmlReport).toBeUndefined();
      expect(result.s3Url).toBeUndefined();
    });
  });

  describe('Edge Cases', () => {
    it('should handle empty XML strings', () => {
      const result = validateXml('', '', mockOpts);
      expect(result.isValid).toBe(true);
    });

    it('should handle complex nested XML', () => {
      const xml = `<catalog><book id="1"><title>Test Book</title><price>29.99</price></book></catalog>`;
      const template = `<catalog><book id="1"><title>Test Book</title><price>29.99</price></book></catalog>`;

      const result = validateXml(xml, template, mockOpts);

      expect(result.isValid).toBe(true);
    });

    it('should handle XML with attributes', () => {
      const xml = '<root attr="value"><item id="1">content</item></root>';
      const template = '<root attr="value"><item id="1">content</item></root>';

      const result = validateXml(xml, template, mockOpts);

      expect(result.isValid).toBe(true);
    });

    it('should detect attribute differences', () => {
      const xml = '<root attr="value1"><item id="1">content</item></root>';
      const template = '<root attr="value2"><item id="2">content</item></root>';

      const result = validateXml(xml, template, mockOpts);

      expect(result.isValid).toBe(false);
      expect(result.differences).toBeDefined();
    });

    it('should handle malformed XML gracefully', () => {
      const xml = '<<<not valid xml at all>>>';
      const template = '<root><name>John</name></root>';

      const result = validateXml(xml, template, mockOpts);

      expect(result.isValid).toBe(false);
      expect(result.differences).toBeDefined();
    });
  });
});

describe('validateXml (type check)', () => {
  it('should return XmlValidationResult type with correct shape', () => {
    const xml = '<root><name>John</name></root>';
    const template = '<root><name>John</name></root>';

    const result: XmlValidationResult = validateXml(xml, template);

    expect(result).toHaveProperty('isValid');
    expect(result).toHaveProperty('method');
    expect('htmlReport' in result || result.htmlReport === undefined).toBe(true);
    expect('s3Url' in result || result.s3Url === undefined).toBe(true);
  });
});
